import {
  BookOpenText,
  Bot,
  Boxes,
  CalendarCheck,
  ChartColumn,
  Clapperboard,
  FileScan,
  LayoutDashboard,
  Megaphone,
  MessageCircle,
  PhoneCall,
  Rocket,
  ScanEye,
  ShoppingBag,
  Sparkles,
  UserSearch,
  UsersRound,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import type { SolutionIcon } from "@/data/services";

export const SOLUTION_ICONS: Record<SolutionIcon, LucideIcon> = {
  bot: Bot,
  crm: UsersRound,
  erp: Boxes,
  doc: FileScan,
  phone: PhoneCall,
  whatsapp: MessageCircle,
  knowledge: BookOpenText,
  marketing: Megaphone,
  insights: ChartColumn,
  shop: ShoppingBag,
  booking: CalendarCheck,
  vision: ScanEye,
  video: Clapperboard,
  workflow: Workflow,
  website: Sparkles,
  mvp: Rocket,
  dashboard: LayoutDashboard,
  hiring: UserSearch,
};
